[build]
builder = "NIXPACKS"
buildCommand = "apt-get update -y && apt-get install -y python3 python3-pip python3-setuptools libpq-dev python3-dev gcc postgresql-client && python3 -m pip install --upgrade pip && cd admin-dashboard && python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "cd admin-dashboard && python3 -m gunicorn app:app"
restartPolicyType = "ON_FAILURE"

[nixpacks]
plan-path = "nixpacks.plan.json" 