[phases.setup]
nixPkgs = ["python310", "postgresql", "gcc"]

[phases.install]
cmds = [
  "cd admin-dashboard && pip install -r requirements.txt"
]

[start]
cmd = "cd admin-dashboard && gunicorn app:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.10" 