[phases.setup]
# Устанавливаем Python и нужные пакеты
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "postgresql", "postgresql.lib", "gcc", "libpqxx"]
aptPkgs = ["libpq-dev", "python3-dev", "gcc", "postgresql-client"]

[phases.install]
# Установка зависимостей
cmds = [
  "python -m pip install --upgrade pip",
  "cd admin-dashboard && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd admin-dashboard && python -m gunicorn app:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.10"
PATH = "/root/.local/bin:$PATH" 