services:
  - type: web
    name: admin-dashboard
    env: python
    buildCommand: cd admin-dashboard && pip install -r requirements.txt
    startCommand: cd admin-dashboard && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: admin_dashboard_secret_key
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true 