[build]
builder = "nixpacks"
buildCommand = "apt-get update -y && apt-get install -y python3-pip libpq-dev gcc librdkafka-dev && pip install -r requirements.txt"

[deploy]
startCommand = "python -m gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[nixpacks]
provider = "python" 